name: OpenWeight Jefit Converter

on:
  push:
    paths:
      - "input/**"

jobs:
  convert-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Run OpenWeight & Convert to CSV
        run: node convert.js

      - name: Save Clean Data
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add output/Cleaned_Jefit_Data.csv
          git commit -m "Converted via OpenWeight" || echo "No changes to commit"
          git push
          
